# Generated by Django 4.2.6 on 2023-11-18 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Endereço de Email')),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Admin'), ('recebimento', 'Recebimento'), ('fiscal', 'Fiscal'), ('comprador', 'Comprador'), ('fornecedor', 'Fornecedor'), ('transportadora', 'Transportadora')], max_length=20, verbose_name='Tipo de Usuário')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('nome_fornecedor', models.CharField(max_length=50, verbose_name='Nome Fornecedor')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('ultimo_login', models.DateTimeField(auto_now=True, verbose_name='Último Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnviosNFs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_compras', models.CharField(max_length=10, verbose_name='Pedido de Compras')),
                ('nota_num', models.CharField(max_length=9, verbose_name='Nota Fiscal')),
                ('pdf_nota', models.FileField(upload_to='', verbose_name='PDF Nota Fiscal')),
                ('empresa_destinataria', models.CharField(choices=[('MULTI FABRICA - 59.717.553/0006-17', 'MULTI FABRICA - 59.717.553/0006-17'), ('MULTI MATRIZ - 59.717.553/0001-02', 'MULTI MATRIZ - 59.717.553/0001-02'), ('MULTI COMPONENTES - 18.272.566/0001-38', 'MULTI COMPONENTES - 18.272.566/0001-38'), ('BLUE - 59.717.553/0012-65', 'BLUE - 59.717.553/0012-65')], max_length=50, verbose_name='Empresa Destino')),
                ('solicitante', models.CharField(max_length=50, verbose_name='Solicitante')),
                ('observacao_fiscal', models.TextField(max_length=200, verbose_name='Observação Fiscal')),
                ('data_divergencia_fiscal', models.DateTimeField(verbose_name='Data da Divergencia')),
                ('data_validacao_fiscal', models.DateTimeField(verbose_name='Data de Validação')),
                ('observacao_compras', models.TextField(max_length=200, verbose_name='Observação Compras')),
                ('data_ajuste_compras', models.DateTimeField(verbose_name='Data de Ajuste')),
                ('observacao_fornecedor', models.TextField(default='Observação', max_length=200, verbose_name='Observação Fornecedor')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('status_envio', models.CharField(choices=[('Ag Fiscal', 'Ag Fiscal'), ('Ag Compras', 'Ag Compras'), ('Ag Agendamento', 'Ag Agendamento'), ('Agendado', 'Agendado'), ('Recebido', 'Recebido'), ('Recusado', 'Recusada'), ('Cancelada', 'Cancelada')], default='Ag Fiscal', max_length=50, verbose_name='Status Envio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='TabelaAgendados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agenda', models.DateField(verbose_name='Data de Agenda')),
                ('hora_agenda', models.TimeField(verbose_name='Hora de Agenda')),
                ('id_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_solen.enviosnfs')),
            ],
        ),
    ]
