# Generated by Django 4.2.6 on 2023-12-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_solen', '0002_alter_enviosnfs_data_ajuste_compras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviosnfs',
            name='observacao_fornecedor',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Observação Fornecedor'),
        ),
    ]
